### ISSUE TITLE
[ENHANCEMENT] UnmarshalSlice fails for large slices

### ISSUE THREAD

**Issue by soptim-erke** [deneonet/benc#3]
**Describe the bug**

First of all, let me thank you for making this awesome library. It has enabled us to do high-performance serialisation and deserialisation of time series data with AWS Lambda. However, during testing, we discovered what we think might be a bug when benchmarking with large datasets.

In particular, unmarshalling slices with a length greather than `MaxUint16` fails. This seems to be due to the fact that, when encoding, only two bytes are reserved for the size of a slice, which is explicitly cast to `uint16`. Because the length of a slice is represented as an `int`, the encoder should at least reserve 4 bytes (though 8 bytes would be better, and in line with what `SizeInt` and `MarshalInt` are doing), or panic if a client wants to encode a slice larger than `MaxUint16`.

**To Reproduce**

I wrote a small test - which I put in `bstd_test.go` locally - to reproduce the issue.

```go
func TestUnmarshalSliceTooLong(t *testing.T) {
	slice := make([]int, math.MaxUint16 + 1)

	slice[0] = 1
	slice[len(slice)-1] = 1

	size := SizeSlice(slice, SizeInt)

	n, buf := Marshal(size)

	n = MarshalSlice(n, buf, slice, MarshalInt)

	n, decoded, err := UnmarshalSlice(0, buf, UnmarshalInt)
	if err != nil {
		t.Fatal(err)
	}
	if err = VerifyUnmarshal(n, buf); err != nil {
		t.Fatal(err)
	}

	if !reflect.DeepEqual(slice, decoded) {
		t.Fatal("not equal")
	}
}
```

Note that this test passes without problems when I change the size of `slice` to simply be `math.MaxUint16`.

**Expected behavior**

The above test should ideally not fail.

**Golang version:**

go version go1.22.1 windows/amd64

**BENC version:**

v1.0.6

**Additional context**

/

**Comment by deneonet** [comment]
Hello, thanks for reporting this issue. Yes I used a uint16 as maximum size for encoding a slice, to reduce the size of the resulting byte slice, which is now when I think of it just bad. Now my idea is to add an option for setting the maximum size?

**Comment by deneonet** [comment]
So this issue should be fixed in `v1.0.7` but I am keeping this issue open, until I added this option for every size/marshal and unmarshal, that needs it.

**Comment by DasPoet** [comment]
I just incorporated the new version into our code and it works like a charm. Thanks so much :heart:

**Comment by introspection3** [comment]
@DasPoet @deneonet dears, Can I use it now without any scruples?

**Comment by DasPoet** [comment]
I would say so. We have been using the new benc version in production for over a month now and have not had any issues so far :)

**Comment by introspection3** [comment]
> I would say so. We have been using the new benc version in production for over a month now and have not had any issues so far :)

thank you very much

**Comment by deneonet** [comment]
Closing with update `v1.0.9`.
