### ISSUE TITLE
[BUG] cross compile on 32bit system met bug

### ISSUE THREAD

**Issue by introspection3** [deneonet/benc#6]
**Describe the bug**
![image](https://github.com/user-attachments/assets/aa7f3a99-bf91-4bd5-a8ad-adadc06d283f)

**To Reproduce**

**Expected behavior**
ok

**Golang version:**
1.22

**BENC version:**
v1.0.7

**Additional context** fix
 
```  go
 func verifySize(l int, ms MaxSize) bool {
	var ll uint = uint(l)
	switch ms {
	case MaxSizeUint16:
		return ll <= math.MaxUint16
	case MaxSizeUint32:
		return ll <= math.MaxUint32
	case MaxSizeInt64:
		return true
	}

	return false
}
```

**Comment by deneonet** [comment]
Hello, thanks for the bug report. I'll fix it on Friday or Saturday.

**Comment by introspection3** [comment]
> Hello, thanks for the bug report. I'll fix it on Friday or Saturday.

hello ,sir ,did you fix it?

**Comment by deneonet** [comment]
Sorry for the delay, I am busy currently. Today, I should be able to finish it.

**Comment by deneonet** [comment]
It's now about a month old and I'm sorry for that, I did a whole restructure and was busy with my life. `v1.1.0` should fix your issue. Please let me know if it doesn't.

**Comment by deneonet** [comment]
Sorry I didn't really understand that.
